version: "3.8"

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=ignite
      - POSTGRES_PASSWORD=arthur
      - POSTGRES_DB=nest-clean
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
